//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteClaculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int Id { get; set; }
        public string LocationStart { get; set; }
        public string LocationEnd { get; set; }
        public decimal RouteLength { get; set; }
        public string City { get; set; }
    
        public virtual City City1 { get; set; }

        public override string ToString()
        {
            return LocationStart
                + " - "
                + LocationEnd;
        }
    }
}
