//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteClaculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes
    {
        public int Id { get; set; }
        public int LocationStart { get; set; }
        public int LocationEnd { get; set; }
        public decimal RouteLength { get; set; }
        public int City { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Locations Locations1 { get; set; }

        public override string ToString()
        {
            return RoutesDatabaseContext.GetLocationById(LocationStart).ToString()
                + " - " + 
                RoutesDatabaseContext.GetLocationById(LocationEnd).ToString();
        }
    }
}
